---
title: "Class 07"
author: "Ethan Williams"
date: "2026-09-16"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Answering the question about data chuncks 

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)
 
jobs = postings |>
  dplyr::select(company, location_state, remote, posted_at, last_seen_at) |>
  dplyr::filter(remote == 1) |>
  dplyr::mutate(
    posted_at = as.Date(posted_at),
    last_seen_at = as.Date(last_seen_at),
    days_open = as.numeric(as.Date(last_seen_at) - as.Date(posted_at))
    )
```


## Demo 

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/scout.db")
postings = DBI::dbReadTable(con, "scout_postings") |> tibble::as_tibble()
DBI::dbDisconnect(con)
 
jobs = postings |>
  dplyr::select(company, title, location_state, remote, category, posted_at, last_seen_at) |>
  dplyr::mutate(dplyr::across(dplyr::ends_with("_at"), as.Date),
                days_open = as.numeric(last_seen_at - posted_at))

jobs

# Which cat is remote friendly
# To answer that, the logic would be as follows
# find the number of jobs per category
# normalize the number of remote jobs by dividing by the total jobs


jobs |>
  # I want to move from unit of analysis being a job posting to a category
  dplyr::group_by(category) |>
  dplyr::summarise(
    postings = dplyr::n(),
    remote_share = mean(remote)
  )


# Among full-time postings, which states have the highest remote share. 

# Based on the vote in class, I will deviate from the answer in the slide 
# By showing the combination of category and state -- this will still give you the answer you want 

jobs |>
  dplyr::group_by(category, location_state) |>
  dplyr::summarise(
    postings = dplyr::n(),
    remote_share = mean(remote) |> round(digits = 2)
    )|>
  dplyr::arrange(dplyr::desc(remote_share)) |>
  na.omit()# to drop the location_state == NA and any other rows that contatin NA




```





## Airbnb

```{r}
con = DBI::dbConnect(RSQLite::SQLite(), "../data/midwest_airbnb.db")
listings = DBI::dbReadTable(con, "listings") |>
  tibble::as_tibble()
DBI::dbDisconnect(con)
dplyr::glimpse(listings)

#1. How many listings per city?
## If the answer is purley based off last class, I can group by city and then count the number of listings in each city

listings |> dplyr::group_by(city) |> dplyr::summarise(count = dplyr::n())
# alternatively, the short cut for the code above
listings |> dplyr::count(city) # count does group by and then n()

# the other option is to simply county the number of times each city occurred in the col city

table(listings$city) # returns a named vector vs above we get a data.frame/tibble


# 2. For entire homes (room_type == "Entire home/apt") that sleep four or more, what is the median price in each city?

listings |>
  dplyr:: filter(
    room_type == "Entire home/apt" & accommodates >=4
  ) |>
  dplyr::group_by(city) |>
  dplyr::summarise(
    median_price = median(price)
    )

#3. Add price_per_person = price / accommodates. Which three listings are cheapest per person? Believe them?

listings |>
  dplyr:: mutate(
    price_per_person = price /accommodates  
  ) |>
  dplyr::select(city, host_name, name, price, accommodates, price_per_person) |>
  dplyr::arrange(
    price_per_person
    )|>
  tail(3)

#4. Which five host_names have the most listings?
# host ids are unique host names are not 

listings |> dplyr::count(host_name, sort = T) 

listings |> dplyr::count(host_name, host_id, sort = T)


```





















